name: ga_package
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Adjust Python version as needed
  - cookiecutter
  - poetry
  - altair=5.2.0
  - attrs=23.2.0
  - jinja2=3.1.3
  - jsonschema=4.20.0
  - markupsafe=2.1.3
  - numpy=1.26.3
  - packaging=23.2
  - pandas=2.1.4
  - pytest >=7.4.4
  - python-dateutil=2.8.2
  - pytz=2023.3.post1
  - six=1.16.0
  - toolz=0.12.0
  - typing-extensions=4.9.0
  - tzdata