name: ga_package
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Adjust Python version as needed
  - poetry=1.7.1
  - altair=5.2.0
  - numpy=1.26.3
  - pandas=2.1.4
  - pytest>=7.4.4
  - cookiecutter=2.5.0